CREATE DATABASE Bank_System;
USE Bank_System;

CREATE TABLE (
    user_id INT NOT NULL PRIMARY KEY ,
    name VARCHAR(100)NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(200) not NULL,
)